### PR TITLE
:tada: New website, yo. :smile: Lorenzo & Wytamma

### PR DESCRIPTION
**Pull request by MboiTui**
Hey everyone,

With a little Push (hehe, see what i did there) from Wytamma, I finally got a raw version of the website up (#2 ).

It's not meant to be the final version. Happy for comments. If you want to do them yourself you are welcome, if not create an issue and I am also happy to do it.

### CODE REVIEW

**Comment by CexyNature** [comment]
Hi @MboiTui and @Wytamma thanks. This is a massive effort 👏 Thanks so much!
This PR is quite huge, I will try to look at this during this week. Do you think would it be possible to add a little bit more details in the description, like a summary of what you have done and the purpose. I know is related to #2 , maybe you could describe what is achieved with this PR. This is mainly with the purpose of having a good history in the repository, so the description and changes can be understood and followed in the future - and also give me more context about the PR functionality 😃  
With the same principle in mind, do you think it would be a good idea to `git rebase` this PR? - so it would be easy to follow the commit history and changes in the main branch?

Info about [git rebase](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) and also [here](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase)

Info about [PR etiquette](https://medium.com/better-programming/git-workflow-etiquette-f22d96b8b0b8) and also [here](https://gist.github.com/mikepea/863f63d6e37281e329f8)

All observations and links above are done and shared with the purpose of learning (myself included) and exercising good practices that in the long run can help us to be more productive in our own projects and collaborations 😄 

Hoping all this makes sense

**Comment by Wytamma** [comment]
Thanks @CexyNature! I think @MboiTui could the `_site` from the PR and the would reduce the line count a lot. Here's the link to the site on @MboiTui's branch https://mboitui.github.io/codertsv.github.io-1/. I don't think a rebase will be that useful because we just deleted everything. Maybe squash merge? Because most of the commits are just getting the site to build on Github.

**Comment by MboiTui** [comment]
Hey @CexyNature.

Thanks for your useful comments! As you can see I am very new to git and github, so I am happy to learn better workflow practices.

I will read those links you shared later this week, and improve my PR accordingly.

In the meantime, I removed the _site folder. That is a result of building the website locally, and it is not needed now that we are building the site through github now.

**Comment by iracooke** [comment]
What a big effort.  Good on you @MboiTui 

I should try and help .. but instead I will just criticise from the side (sorry).  I have to say that I reckon you should try to keep more information on the front page of the site.  The way it is setup at the moment it does look nicer than before but I worry that it is less functional.  Most people will want links to the presentations and I reckon we should not make them click deeper to find them.

**Comment by Wytamma** [comment]
@iracooke and @CexyNature I think these suggestions are great, but in the sprit of getting things moving I might just merge what we have. We can use issues and PRs to make future changes and suggestions. Right now we just need a minimal working product not a perfect design (that can come later). @MboiTui sound good to you? Let me know if any of you have any objections, otherwise, I'll merge on the weekend so we have the site available for the meeting on Monday.

**Comment by MboiTui** [comment]
Hey all,

Apologies for not implementing those suggestions yet. I am still learning how to juggle multiple projects during a PhD. 

I would like to try and implement at least a few of those before we merge. Can you give me till Sunday late afternoon/night? I'll try and use Sunday to implement some of the suggested changes and tidy up the PR

**Comment by Wytamma** [comment]
No worries @MboiTui, please put your PhD first. The beauty (and curse) of a github project is that it's never finished! We can always make the changes later, there's no need put this ahead of anything else. What we have now is a perfect start. I will wait until you're ready, but don't feel any pressure. I would actually prefer to break the suggested changes up into more atomic PRs so it's easier to follow the progression. I'll contact you on Sunday to see how it's going.

**Comment by CexyNature** [comment]
Adding to what @Wytamma said, @MboiTui please feel free to ask for help in any specific feature you consider can be coded/formatted by someone else :smile:

**Comment by Wytamma** [comment]
I will create new issues for the comments you have raised above.

**Pull request merged**
